# Generated by Django 2.0.9 on 2019-09-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='mes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
