# Generated by Django 2.0.9 on 2019-09-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20190902_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='mes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
