# Generated by Django 2.0.9 on 2019-07-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='finish',
            field=models.DateTimeField(help_text='Date and time of stop', null=True, verbose_name='event_date'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='gas',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stop',
            name='comments',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
