# Generated by Django 2.0.9 on 2019-07-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20190716_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='contact',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
