# Generated by Django 2.0.9 on 2019-08-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_busroute_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='mes',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
