# Generated by Django 2.0.9 on 2019-09-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20190902_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
